services:
  basket_balancer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    networks:
      - basket_network
    command: ["cargo", "run", "--release", "--bin", "basket_balancer"]
  basket_service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    networks:
      - basket_network
    command: ["cargo", "run", "--release", "--bin", "basket_service"]
    depends_on:
      - basket_balancer

networks:
  basket_network:
    driver: bridge

