services:
  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6379:6379"
    networks:
      - basket_network
  basket_service_integration_testing:
    build:
      context: .
      dockerfile: docker/IntegrationTesting_Dockerfile
    environment:
      - REDIS_HOSTNAME=redis
    networks:
      - basket_network
    depends_on:
      - redis

networks:
  basket_network:
    driver: bridge

