syntax = "proto3";

package ap_request;

enum FailureStatus {
    PRODUCT_NOT_FOUND = 0;
    HOLDERS_QUEUE_NOT_FULL_YET = 1;
    USER_ALREADY_ADDED = 2;
    PREMATURE_AWAIT = 3;
    QUEUE_POSITION_IS_INCORRECT = 4;
}

message Request {
  string user_id = 1;
  int32 product_id = 2;
  uint32 queue_position = 3;
}

message Response {
  oneof response {
    Success success = 1;
    Failure failure = 2;
  }
}

message Success {
  string user_id = 1;
  int32 product_id = 2;
  uint32 queue_position = 3; // return queue_position to send it in a response to client
}

message Failure {
  string error_message = 1;
  FailureStatus status = 2;
}
