syntax = "proto3";

package hp_request;

enum SuccessStatus {
    PRODUCT_HELD_BY_USER = 0;
    PRODUCT_AWAITED_BY_USER = 1;
}

enum FailureStatus {
    HOLDERS_QUEUE_ALREADY_FULL = 0;
    PRODUCT_NOT_FOUND = 1;
    PREMATURE_AWAIT = 2;
    USER_ALREADY_ADDED = 3;
    QUEUE_POSITION_IS_INCORRECT = 4;
}

message Request {
  string user_id = 1;
  int32 product_id = 2;
  // optional uint32 queue_position = 3; TODO: queue_position should be present only in ap_request
}

message Response {
  oneof response {
    Success success = 1;
    Failure failure = 2;
  }
}

message Success {
  uint32 user_id = 1;
  uint32 product_id = 2;
  uint32 queue_position = 3;
  SuccessStatus status = 4;
}

message Failure {
  string error_message = 1;
  FailureStatus status = 2;
}
