syntax = "proto3";

package ru_request;

enum FailureStatus {
    USER_NOT_FOUND = 0;
    PRODUCT_NOT_FOUND = 1;
    LOGGED_INTERNALLY_ERROR = 2;
}

message Request {
  string user_id = 1;
  int32 product_id = 2;
}

message Response {
  oneof response {
    Success success = 2;
    Failure failure = 3;
  }
}

message HaInfo {
  uint32 free_holder_places = 1;
  uint32 awaiters_count = 2;
}

message QueueShift {
  string user_id = 1;
  optional uint32 new_queue_position = 2;
}

message Success {
  string removed_user_id = 1;
  optional uint32 removed_user_queue_position = 2;
  repeated QueueShift queue_shifts = 3;
  optional HaInfo ha_info = 4;
}

message Failure {
  optional HaInfo ha_info = 1; // None when product does not exist
  FailureStatus status = 2;
}
