syntax = "proto3";

package sq_request;

enum FailureStatus {
    PRODUCT_NOT_FOUND = 0;
}

message Request {
  int32 product_id = 1;
  optional uint32 max_removed_queue_position = 2; // None if holder was removed but we still need to call the request to rearrange awaiters from other baskets
  uint32 shift = 3;
  uint32 force_removed_awaiters_count = 4;
}

message Response {
  oneof response {
    Success success = 1;
    Failure failure = 2;
  }
}

message QueueShift {
  string user_id = 1;
  optional uint32 new_queue_position = 2;
}

message ForceRemovedAwaiter {
  string user_id = 1;
  int32 product_id = 2;
}

message Success {
  optional ForceRemovedAwaiter force_removed_awaiter = 1; // returns the force-removed awaiter in case we asked to remove one
  repeated QueueShift queue_shifts = 2;
}

message Failure {
  FailureStatus status = 1;
}
